// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ShareRegister.Core.Tests.Common.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Company")]
    public partial class CompanyFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "Company.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Common/Features", "Company", "Create and manage company objects", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Create a valid company]")]
        [NUnit.Framework.CategoryAttribute("common")]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "123456", null)]
        public virtual void CreateAValidCompany(string companyCode, string name, string iSIN, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "common"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Create a valid company]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "Street",
                            "6875"});
                table1.AddRow(new string[] {
                            "Surburb",
                            "Madokero"});
                table1.AddRow(new string[] {
                            "City",
                            "Harare"});
                table1.AddRow(new string[] {
                            "Country",
                            "Zimbabwe"});
                table1.AddRow(new string[] {
                            "PostalCode",
                            "263"});
#line 8
 testRunner.When("the Address is", ((string)(null)), table1, "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "TelephoneNumber",
                            "TelephoneNumberType"});
                table2.AddRow(new string[] {
                            "123456",
                            "Mobile"});
                table2.AddRow(new string[] {
                            "78910",
                            "Landline"});
                table2.AddRow(new string[] {
                            "11111",
                            "VoIP"});
#line 15
 testRunner.And("the telephone numbers are", ((string)(null)), table2, "And ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table3.AddRow(new string[] {
                            "fmashozhera@gmail.com"});
#line 20
 testRunner.And("the email address", ((string)(null)), table3, "And ");
#line hidden
#line 23
 testRunner.When("I create a company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
 testRunner.Then("I should get a success Company result with", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Create a invalid company]")]
        [NUnit.Framework.TestCaseAttribute("", "Mashozhera Holdings", "123456", "CompanyCode is required.", null)]
        [NUnit.Framework.TestCaseAttribute("Mash", "", "123456", "Name is required.", null)]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "", "ISIN is required.", null)]
        public virtual void CreateAInvalidCompany(string companyCode, string name, string iSIN, string errorMessage, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            argumentsOfScenario.Add("ErrorMessage", errorMessage);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Create a invalid company]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 31
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table4.AddRow(new string[] {
                            "Street",
                            "6875"});
                table4.AddRow(new string[] {
                            "Surburb",
                            "Madokero"});
                table4.AddRow(new string[] {
                            "City",
                            "Harare"});
                table4.AddRow(new string[] {
                            "Country",
                            "Zimbabwe"});
                table4.AddRow(new string[] {
                            "PostalCode",
                            "263"});
#line 32
 testRunner.When("the Address is", ((string)(null)), table4, "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "TelephoneNumber",
                            "TelephoneNumberType"});
                table5.AddRow(new string[] {
                            "123456",
                            "Mobile"});
                table5.AddRow(new string[] {
                            "78910",
                            "Landline"});
                table5.AddRow(new string[] {
                            "11111",
                            "VoIP"});
#line 39
 testRunner.And("the telephone numbers are", ((string)(null)), table5, "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table6.AddRow(new string[] {
                            "fmashozhera@gmail.com"});
#line 44
 testRunner.And("the email address", ((string)(null)), table6, "And ");
#line hidden
#line 47
 testRunner.When("I create a with invalid company details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 48
 testRunner.Then(string.Format("I should get a failure Company result with message \'{0}\'", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Create a company with no address]")]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "123456", "Address is required.", null)]
        public virtual void CreateACompanyWithNoAddress(string companyCode, string name, string iSIN, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Create a company with no address]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "TelephoneNumber",
                            "TelephoneNumberType"});
                table7.AddRow(new string[] {
                            "123456",
                            "Mobile"});
                table7.AddRow(new string[] {
                            "78910",
                            "Landline"});
                table7.AddRow(new string[] {
                            "11111",
                            "VoIP"});
#line 58
 testRunner.And("the telephone numbers are", ((string)(null)), table7, "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table8.AddRow(new string[] {
                            "fmashozhera@gmail.com"});
#line 63
 testRunner.And("the email address", ((string)(null)), table8, "And ");
#line hidden
#line 66
 testRunner.When("I create a with company no address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 68
 testRunner.Then(string.Format("I should get a failure Company result with message \'{0}\'", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Create a company with no telephone numbers]")]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "123456", "Telephone numbers are required.", null)]
        public virtual void CreateACompanyWithNoTelephoneNumbers(string companyCode, string name, string iSIN, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Create a company with no telephone numbers]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 74
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 75
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table9.AddRow(new string[] {
                            "Street",
                            "6875"});
                table9.AddRow(new string[] {
                            "Surburb",
                            "Madokero"});
                table9.AddRow(new string[] {
                            "City",
                            "Harare"});
                table9.AddRow(new string[] {
                            "Country",
                            "Zimbabwe"});
                table9.AddRow(new string[] {
                            "PostalCode",
                            "263"});
#line 76
 testRunner.When("the Address is", ((string)(null)), table9, "When ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table10.AddRow(new string[] {
                            "fmashozhera@gmail.com"});
#line 83
 testRunner.And("the email address", ((string)(null)), table10, "And ");
#line hidden
#line 86
 testRunner.When("I create a with invalid company details with no telephone numbers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 88
 testRunner.Then(string.Format("I should get a failure Company result with message \'{0}\'", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Create a company with no email]")]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "123456", "Email is required.", null)]
        public virtual void CreateACompanyWithNoEmail(string companyCode, string name, string iSIN, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Create a company with no email]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 93
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 94
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table11.AddRow(new string[] {
                            "Street",
                            "6875"});
                table11.AddRow(new string[] {
                            "Surburb",
                            "Madokero"});
                table11.AddRow(new string[] {
                            "City",
                            "Harare"});
                table11.AddRow(new string[] {
                            "Country",
                            "Zimbabwe"});
                table11.AddRow(new string[] {
                            "PostalCode",
                            "263"});
#line 95
 testRunner.When("the Address is", ((string)(null)), table11, "When ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "TelephoneNumber",
                            "TelephoneNumberType"});
                table12.AddRow(new string[] {
                            "123456",
                            "Mobile"});
                table12.AddRow(new string[] {
                            "78910",
                            "Landline"});
                table12.AddRow(new string[] {
                            "11111",
                            "VoIP"});
#line 102
 testRunner.And("the telephone numbers are", ((string)(null)), table12, "And ");
#line hidden
#line 107
 testRunner.When("I create a company with no email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 108
 testRunner.Then(string.Format("I should get a failure Company result with message \'{0}\'", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Update a valid company]")]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "123456", null)]
        public virtual void UpdateAValidCompany(string companyCode, string name, string iSIN, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Update a valid company]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 115
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 116
 testRunner.Given("I have a valid company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 117
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table13.AddRow(new string[] {
                            "Street",
                            "6875"});
                table13.AddRow(new string[] {
                            "Surburb",
                            "Madokero"});
                table13.AddRow(new string[] {
                            "City",
                            "Harare"});
                table13.AddRow(new string[] {
                            "Country",
                            "Zimbabwe"});
                table13.AddRow(new string[] {
                            "PostalCode",
                            "263"});
#line 118
 testRunner.When("the Address is", ((string)(null)), table13, "When ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "TelephoneNumber",
                            "TelephoneNumberType"});
                table14.AddRow(new string[] {
                            "123456",
                            "Mobile"});
                table14.AddRow(new string[] {
                            "78910",
                            "Landline"});
                table14.AddRow(new string[] {
                            "11111",
                            "VoIP"});
#line 125
 testRunner.And("the telephone numbers are", ((string)(null)), table14, "And ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table15.AddRow(new string[] {
                            "fmashozhera@gmail.com"});
#line 130
 testRunner.And("the email address", ((string)(null)), table15, "And ");
#line hidden
#line 133
 testRunner.When("I update a company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 134
 testRunner.Then("I should get a success Company result with", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Update a invalid company]")]
        [NUnit.Framework.TestCaseAttribute("", "Mashozhera Holdings", "123456", "CompanyCode is required.", null)]
        [NUnit.Framework.TestCaseAttribute("Mash", "", "123456", "Name is required.", null)]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "", "ISIN is required.", null)]
        public virtual void UpdateAInvalidCompany(string companyCode, string name, string iSIN, string errorMessage, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            argumentsOfScenario.Add("ErrorMessage", errorMessage);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Update a invalid company]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 140
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 141
 testRunner.Given("I have a valid company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 142
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table16.AddRow(new string[] {
                            "Street",
                            "6875"});
                table16.AddRow(new string[] {
                            "Surburb",
                            "Madokero"});
                table16.AddRow(new string[] {
                            "City",
                            "Harare"});
                table16.AddRow(new string[] {
                            "Country",
                            "Zimbabwe"});
                table16.AddRow(new string[] {
                            "PostalCode",
                            "263"});
#line 143
 testRunner.When("the Address is", ((string)(null)), table16, "When ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "TelephoneNumber",
                            "TelephoneNumberType"});
                table17.AddRow(new string[] {
                            "123456",
                            "Mobile"});
                table17.AddRow(new string[] {
                            "78910",
                            "Landline"});
                table17.AddRow(new string[] {
                            "11111",
                            "VoIP"});
#line 150
 testRunner.And("the telephone numbers are", ((string)(null)), table17, "And ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table18.AddRow(new string[] {
                            "fmashozhera@gmail.com"});
#line 155
 testRunner.And("the email address", ((string)(null)), table18, "And ");
#line hidden
#line 158
 testRunner.When(string.Format("I update a with invalid company details \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 159
 testRunner.Then(string.Format("I should get a failure Company result with message \'{0}\'", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Update a company with no address]")]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "123456", "Address is required.", null)]
        public virtual void UpdateACompanyWithNoAddress(string companyCode, string name, string iSIN, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Update a company with no address]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 167
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 168
 testRunner.Given("I have a valid company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 169
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "TelephoneNumber",
                            "TelephoneNumberType"});
                table19.AddRow(new string[] {
                            "123456",
                            "Mobile"});
                table19.AddRow(new string[] {
                            "78910",
                            "Landline"});
                table19.AddRow(new string[] {
                            "11111",
                            "VoIP"});
#line 170
 testRunner.And("the telephone numbers are", ((string)(null)), table19, "And ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table20.AddRow(new string[] {
                            "fmashozhera@gmail.com"});
#line 175
 testRunner.And("the email address", ((string)(null)), table20, "And ");
#line hidden
#line 178
 testRunner.When("I update a with company no address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 180
 testRunner.Then(string.Format("I should get a failure Company result with message \'{0}\'", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Update a company with no telephone numbers]")]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "123456", "Telephone numbers are required.", null)]
        public virtual void UpdateACompanyWithNoTelephoneNumbers(string companyCode, string name, string iSIN, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Update a company with no telephone numbers]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 186
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 187
 testRunner.Given("I have a valid company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 188
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table21.AddRow(new string[] {
                            "Street",
                            "6875"});
                table21.AddRow(new string[] {
                            "Surburb",
                            "Madokero"});
                table21.AddRow(new string[] {
                            "City",
                            "Harare"});
                table21.AddRow(new string[] {
                            "Country",
                            "Zimbabwe"});
                table21.AddRow(new string[] {
                            "PostalCode",
                            "263"});
#line 189
 testRunner.When("the Address is", ((string)(null)), table21, "When ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table22.AddRow(new string[] {
                            "fmashozhera@gmail.com"});
#line 196
 testRunner.And("the email address", ((string)(null)), table22, "And ");
#line hidden
#line 199
 testRunner.When("I update a with invalid company details with no telephone numbers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 201
 testRunner.Then(string.Format("I should get a failure Company result with message \'{0}\'", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[Update a company with no email]")]
        [NUnit.Framework.TestCaseAttribute("Mash", "Mashozhera Holdings", "123456", "Email is required.", null)]
        public virtual void UpdateACompanyWithNoEmail(string companyCode, string name, string iSIN, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CompanyCode", companyCode);
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("ISIN", iSIN);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Update a company with no email]", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 206
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 207
 testRunner.Given("I have a valid company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 208
 testRunner.Given(string.Format("I capture the  valid values \'{0}\',\'{1}\',\'{2}\'", companyCode, name, iSIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table23.AddRow(new string[] {
                            "Street",
                            "6875"});
                table23.AddRow(new string[] {
                            "Surburb",
                            "Madokero"});
                table23.AddRow(new string[] {
                            "City",
                            "Harare"});
                table23.AddRow(new string[] {
                            "Country",
                            "Zimbabwe"});
                table23.AddRow(new string[] {
                            "PostalCode",
                            "263"});
#line 209
 testRunner.When("the Address is", ((string)(null)), table23, "When ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "TelephoneNumber",
                            "TelephoneNumberType"});
                table24.AddRow(new string[] {
                            "123456",
                            "Mobile"});
                table24.AddRow(new string[] {
                            "78910",
                            "Landline"});
                table24.AddRow(new string[] {
                            "11111",
                            "VoIP"});
#line 216
 testRunner.And("the telephone numbers are", ((string)(null)), table24, "And ");
#line hidden
#line 221
 testRunner.When("I update a company with no email address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 222
 testRunner.Then(string.Format("I should get a failure Company result with message \'{0}\'", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
